[project]
name = "mutants"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0",
    "rich>=13.7",
    "click>=8.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.5",
]

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
addopts = "-q"
